# NumPy
NumPy is a Python Library which offers a range of mathematical functions.
NumPy has a syntax which is simultaneously compact, powerful and expressive. It allows users to manage data in vectors, matrices and higher dimensional arrays.

# Creating an Array using NumPy

In [2]:
import numpy as np #imports numpy

In [3]:
x = np.array([1,2,3,4]) #defining 1-D array
print(x)
y = np.array([[1,2,3,0],[4,5,6,14],[12,13,15,16],[11,7,9,10]]) #defining 2-D array
print(y)

[1 2 3 4]
[[ 1  2  3  0]
 [ 4  5  6 14]
 [12 13 15 16]
 [11  7  9 10]]


## Functions on Array

In [4]:
x.shape #shape function returns number of rows and colums of an array

(4,)

In [5]:
y.shape

(4, 4)

In [6]:
y.dtype #dtype function returns data type of the array

dtype('int32')

#### Function to Acess Elements at Specific Index

In [7]:
y[1,1]  #gives element at index (1,1) i.e. Row 1 Column 1 in array y

5

In [8]:
y[2,:] #This will return all elements of row 2 in the form of array

array([12, 13, 15, 16])

#### Intialising arrays using some in-built functions

In [9]:
zeros = np.zeros((1,4)) #This function will generate an array with 1 row and 4 columns with all 0 values.
print(zeros)

[[0. 0. 0. 0.]]


In [10]:
one = np.ones((2,5)) #This function will generate an array with 2 row and 5 columns with all 1 values.
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
random = np.random.rand(2,2) #This function will generate an array with 2 row and 2 columns all random elements.
print(random)

[[0.85191043 0.92657634]
 [0.80535181 0.92194349]]


In [12]:
id = np.identity(3) ##This function will generate an Identity Matrix with 3 row and 3 columns.
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Scalar Operations on 2D Matrix

In [13]:
print(y+2)  # perform arithematic operaions on all the values of the matrix
print(y-4)
print(y*3)
print(y/2)
print(y**2)

[[ 3  4  5  2]
 [ 6  7  8 16]
 [14 15 17 18]
 [13  9 11 12]]
[[-3 -2 -1 -4]
 [ 0  1  2 10]
 [ 8  9 11 12]
 [ 7  3  5  6]]
[[ 3  6  9  0]
 [12 15 18 42]
 [36 39 45 48]
 [33 21 27 30]]
[[0.5 1.  1.5 0. ]
 [2.  2.5 3.  7. ]
 [6.  6.5 7.5 8. ]
 [5.5 3.5 4.5 5. ]]
[[  1   4   9   0]
 [ 16  25  36 196]
 [144 169 225 256]
 [121  49  81 100]]


#### Matrix Operations

In [14]:
s1 = np.array([[1,2,3],[4,6,2],[0,7,1]])
s2 = np.array([[3,6,9],[1,4,5],[7,2,1]])

print(s1+s2) #performs matrix addition
p = np.matmul(s1,s2)
print(p) #performs matrix multiplication between s1 and s2

[[ 4  8 12]
 [ 5 10  7]
 [ 7  9  2]]
[[26 20 22]
 [32 52 68]
 [14 30 36]]


In [15]:
np.min(s2) # returns min value in s2

1

In [16]:
np.max(s2) # returns max value in s2

9

#### Concept Of Axis in Arrays.
A 1D array has only 1 Axis (Axis 0) along its row.  
A 2D array has 2 Axis (Axis 0, Axis 1) Axis 1 along its row and Axis 0 along its columns.

In [17]:
np.sum(s2,axis=0)  #To add all elements of a column

array([11, 12, 15])

In [18]:
np.sum(s2,axis=1) #To add all elements of a row

array([18, 10, 10])

### Changing shape of an array

In [19]:
w1 = s1
print(w1.reshape(9,1)) #reshapes w1 into 9X1 Matrix
print(s2)

[[1]
 [2]
 [3]
 [4]
 [6]
 [2]
 [0]
 [7]
 [1]]
[[3 6 9]
 [1 4 5]
 [7 2 1]]


#### Transpose of the Matrix.

In [20]:
s1.T

array([[1, 4, 0],
       [2, 6, 7],
       [3, 2, 1]])