# NumPy

NumPy is a python library used for working with arrays. NumPy stands for Numerical Python. It makes working wih arrays easier and faster.

### Creating NumPy arrays

You can create a single dimensional or a multidimentional array.

> Import NumPy library. The name after **as** refers to an alias name for the library.

In [1]:
import numpy as np

In [3]:
n1 = np.array([1,2,3,4])     #this is array() method used to create ndarray objects

In [4]:
n1

array([1, 2, 3, 4])

In [8]:
n2 = np.array([[1,2],[3,4]])

In [9]:
n2

array([[1, 2],
       [3, 4]])

> Initializing the array with zeroes. For this we use the zeros method

In [12]:
n3 = np.zeros((1,2))             #the argument is the dimension of the array
n3

array([[0., 0.]])

In [13]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

>Initializing the array with the same number. For this we use full method

In [14]:
n5 = np.full((3,4),10)       #arguments as the dimension of the array and the number to be initialized with
n5

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

>Intializing with random numbers -> random.randint

In [16]:
n6 = np.random.randint(1,100,7)     #1- 100 is the range of the numbers and 7 is the how many numbers we need
n6

array([84, 89, 99,  7, 89, 67, 40])

### Shape of the arrays

>Using shape() method we can get the dimension of the arrays and can even reshape them.

In [19]:
n5.shape

(3, 4)

In [20]:
n5.shape = (4,3)
n5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Array intersection and difference

In [22]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50, 60,70,80])

In [23]:
np.intersect1d(n1,n2)       #gives us the common elements of n1 and n2

array([50, 60])

In [24]:
np.setdiff1d(n1,n2)         #gives the elements unique to n1

array([10, 20, 30, 40])

In [25]:
np.setdiff1d(n2,n1)         #gives the elements unique to n2

array([70, 80])

### Mathematical operations on arrays

Addition of the arrays

In [35]:
n1 = np.array([10,50])
n2 = np.array([30,70])
np.sum([n1,n2])

160

In [36]:
np.sum([n1,n2],axis = 0)    #axis 0 to get sum along the columns

array([ 40, 120])

In [37]:
np.sum([n1,n2],axis = 1)    #to add values along the rows

array([ 60, 100])

In [50]:
n1 = np.array([10,20,30])     
n1 

array([10, 20, 30])

In [51]:
n1 = n1+1                 #add 1 to all elements of the array. Simmilarly we can perform other operations like -,*,/
n1

array([11, 21, 31])

### Matrices

In [52]:
n1 = np.array([[10,20],[20,30],[40,50]])
n1

array([[10, 20],
       [20, 30],
       [40, 50]])

In [53]:
n1[0]           #entire 1st row

array([10, 20])

In [55]:
n1[:,1]        #all rows for column2

array([20, 30, 50])

In [56]:
np.transpose(n1)      #get the transpose of the matrix
n1

array([[10, 20],
       [20, 30],
       [40, 50]])


>Matrix multiplication

In [59]:
n2 = np.array([[1,2,3],[3,4,5]])
n2

array([[1, 2, 3],
       [3, 4, 5]])

In [60]:
n1.dot(n2)

array([[ 70, 100, 130],
       [110, 160, 210],
       [190, 280, 370]])

In [61]:
n2.dot(n1)

array([[170, 230],
       [310, 430]])

Similarly there are many more methods out there to perform various functions on arrays easily and in less time.