# Numpy stuff

- Numpy is one of the major libraries used in machine learning and data science. It is used for a variety of mathematical computations by helping us with large n-dimensional arrays.

- So it comes pre-installed with your Anaconda package.

- Have a look at its [documentation](https://numpy.org/doc/)

- You just need to import the libraries like:

In [1]:
import numpy as np

- We can create a numpy array with the ```np.array()``` constructor with a regular Python list as its argument

In [2]:
a1 = np.array([1,2,3,4])

- Then you could implement functions like ```a1.shape``` to get the shape of an array

In [4]:
a1.shape

(4,)

- In this case, the array above is uni-dimensional, also called a flat-array. We can also use a list of list to obtain a more clear matrix-like shape:

In [5]:
a2 = np.array([[1,2,3,4]])
a2.shape

(1, 4)

- Now similarly initiate a column matrix

In [6]:
a3 = np.array([[1],[2],[3],[4]])
a3.shape

(4, 1)

- Or maybe a full matrice the same way

In [8]:
M1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("M1 = ", M1)
M1.shape

M1 =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

### Some more functions

    1. np.reshape

In [11]:
M2 = np.reshape(M1, (1,12)) #reshaping matrix M1 to a row Matrix M2
print("M2 = ", M2)

M2 =  [[ 1  2  3  4  5  6  7  8  9 10 11 12]]


- As you can see this works only when the number of elements dont change

    2. np.dot

- You may be familiar with the dot product and its rules. Here we find 'a3.a2'

In [12]:
Dot_res1 = np.dot(a3,a2)
print("Dot product = ", Dot_res1)
Dot_res1.shape

Dot product =  [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


(4, 4)

In [13]:
Dot_res2 = np.dot(a2,a3)
print("Dot product = ", Dot_res2)
Dot_res2.shape

Dot product =  [[30]]


(1, 1)

    3. np.random

In [14]:
M3 = np.random.randn(3,4) #Generates a random matrix of dimension (3,4)

In [16]:
print("M3 = ", M3)

M3 =  [[-1.63637147  0.55883515 -0.7049998   0.6285767 ]
 [ 0.46119871  0.03205836 -0.80597492  0.65375346]
 [-0.55514165 -0.14671001  0.12533635  0.1352804 ]]


- You can try and explore more such functions