<h1>Numpy</h1><br>
NumPy (Numerical Python) is an open source Python library. It contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays

The first step is to import the <b>Numpy</b> library to the current jupyter notebook.

In [2]:
import numpy as np #Shorthand notation given to facilitate easier further usage.

<h2>Array</h2>

A numpy array is a data structure which is similar to python lists, and it has a grid of elements that can be accesed in various ways.<br>
An array object in NumPy is called <b>ndarray</b>.

In [14]:
a=np.array([1,2,3,4])  #Initialising a 1D array.
print(type(a)) #returns type numpy.ndarray
b= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #Initialising a multi-dimensioanl array(3 dimensional in this case.)
print(a) #To print the whole array.
print(b)
print(a[0]) #using indexing to print an element of the array.

c=np.arange(4) #used to create an arrayof range of elements.
print(c)

d=np.linspace(0,10,num=3) #creats an array with values that are spaced linearly in a specified interval.
print(d)

#To print a single element of a multidimensional array, multidimensional indexing is required.
print(b[0]) #prints the 0th element of the 3-D array which in itself is a 1-D array.
print(b[0][1]) #prints the second element of the first 1-D array.

#negative indexing using numpy
print(b[1][-1]) #prints the last element from ther second dimension.

#Slicing of arrays created using numpy 
print(a[:3]) #prints an array containing first 3 elements of the array.
print(a[1:2]) #prints the second element in the array.
print(a[2:]) #prints the element from the index 2 to the last element.
print(a[-3:-1]) #Slices the array from index 3 from the end to index 1 from the end.
#Similarly 2d arrays can be sliced.



<class 'numpy.ndarray'>
[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[0 1 2 3]
[ 0.  5. 10.]
[1 2 3 4]
2
8
[1 2 3]
[2]
[3 4]
[2 3]


In [17]:
#sorting a numpy array
e = np.array([5,4,8,7,3,2,6]) #sorts the array in ascending order.
print(np.sort(e))

#concatenate two arrays
f=np.concatenate((a,e))
print(f)

[2 3 4 5 6 7 8]
[1 2 3 4 5 4 8 7 3 2 6]


### Shape and size of an array

In [32]:
print(np.shape(b)) #returns the shape of the aray
print(np.ndim(b)) #returns the dimension of the array
print(np.size(b)) #returns the number of elements in the array.

#reshaping the array

g = b.reshape(6,2) #an array can be reshaoped as long as the new array has the same number of elements.
print(g)

#This can also be done by using np.reshape, some few more parameters can also be specified.
h= np.reshape(b, newshape=(2,6))
print(h)

(3, 4)
2
12
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Adding axis to an array

In [39]:
#Converting 1D array to 2D array
print(a.shape)

#np.newaxis
a2=a[np.newaxis, :] #1D array converted to a row vector. Similarly it can be turned into a column vector.
print(a2)

#np.expand_dims
a3=np.expand_dims(a,axis=0)
print(a3.shape)

a4=np.expand_dims(a,axis =1)
print(a4.shape)




(4,)
[[1 2 3 4]]
(1, 4)
(4, 1)


### Creating an array from existing data


In [53]:
#stacking of arrays
b1=([5,4],[6,2])
b2=([1,2],[3,4])
print(np.vstack((b1,b2))) #vertical stacking of the two arrays

print(np.hstack((b1,b2))) #horizontal stacking of the arrays


#view method - any changes made to the original array will affect the original array
print(b)

b_new=b[0,:]
print(b_new)
b_new[0]=5
print(b_new)
print(b) #original array is modified


#copy method- any changes made in the copied array will not modify the original array
b_copy=b.copy()
print(b_copy)
b_copy_new=b_copy[1,:]
print(b_copy_new)
b_copy_new[2]=9
print(b_copy_new)
print(b) #remains the same.


[[5 4]
 [6 2]
 [1 2]
 [3 4]]
[[5 4 1 2]
 [6 2 3 4]]
[[ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 2 3 4]
[5 2 3 4]
[[ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[5 6 9 8]
[[ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Basic Array Operations

In [55]:
#Addition
arr=np.array([1,2])
arr_1=np.ones(2,dtype=int)
print(arr+arr_1)

#Similarly Subtraction, Divison and Multiplication can be carried out


[2 3]


### Broadcasting

In [57]:
print(arr*4) #operation carried out between an array and single number

[4 8]


### Creating matrices

In [58]:
print(b)

[[ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
print(b[0,1])
print(b[1:3])
print(b[0:2,0])

2
[[ 5  6  7  8]
 [ 9 10 11 12]]
[5 5]


In [61]:
print(b.max())
print(b.min())
print(b.sum())
print(b.prod(axis=0))


12
2
82
[225 120 231 384]


In [69]:
print(b)
print(np.unique(b)) #prints unique elements in a numpy array
print(np.unique(a,return_index=True))

[[ 5  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  3  4  5  6  7  8  9 10 11 12]
(array([1, 2, 3, 4]), array([0, 1, 2, 3], dtype=int64))
