# Numpy

1. Numpy provides a lot of functions to work in the domain of Linear Algebra, Matrices, Fourier transform 
   and more.
2. It is a Python library used for working with arrays and functions related to arrays.
3. Most of the part of the Numpy library is created using C & C++.

## Working with Numpy

### Creating an array

In [1]:
import numpy as np # imports Numpy 

#### 0 dimensional array-

In [11]:
a=np.array(21)
print(a)
print(a.ndim)# printing dimension of array
a.shape      #gives size of array

21
0


()

#### 1 dimensional array-

In [16]:
b=np.array([1,2,3])
print(b)
print(b.ndim)
b.shape

[1 2 3]
1


(3,)

#### 2 dimensional array-

In [19]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.ndim)
c.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

#### 3 dimensional array-

In [20]:
d=np.array([[[1,2],[3,4],[1,8]],[[2,8],[5,6],[6,7]]])
print(d)
print(d.ndim)
d.shape

[[[1 2]
  [3 4]
  [1 8]]

 [[2 8]
  [5 6]
  [6 7]]]
3


(2, 3, 2)

#### Function to access specific element 

**Index start from 0 and not 1.**

In [23]:
b[2]

3

In [27]:
c[0,0]

1

In [28]:
d[0,1,1]

4

In [51]:
c[:,2] #prints 3rd column of matrix


array([3, 6])

In [50]:
c[1,:] #prints 2nd row of given matrix

array([4, 5, 6])

In [53]:
d[1,:,:] 

array([[2, 8],
       [5, 6],
       [6, 7]])

In [56]:
d[1,2,:]

array([6, 7])

#### Arrays with numerical range
 Format - np.arrange(start index,stop index,step size,dtype)
 
**Stop index is not included in array.**

**If data type is not specified then default data type(int) is taken.**

In [35]:
q=np.arange(0,10,2)
p=np.arange(5,11,1,dtype="int")
print(q)
print(p)

[0 2 4 6 8]
[ 5  6  7  8  9 10]


#### Matrix operations

In [37]:
w=np.array([1,2,8])
r=np.array([4,5,9])
print(w+r) #prints sum of matrices
print(a+w+r)

[ 5  7 17]
[26 28 38]


In [39]:
t=np.matmul(w,r) #matrix multiplication between w & r
print(t)

86


In [42]:
e=np.min(b) #gives minimum value in a matrix
y=np.min(d)
g=np.max(d) # gives maximum value in a matrix
print(e)
print(y)
print(g)

1
1
8


In [43]:
c.T # gives transpose of a matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
print(d+1)# adds 1 to all elements of given matrix
print(b-2)
print(b/2)#divides every element of given matrix
print(b*2)#multiplies every element of given matrix

[[[2 3]
  [4 5]
  [2 9]]

 [[3 9]
  [6 7]
  [7 8]]]
[-1  0  1]
[0.5 1.  1.5]
[2 4 6]
