# Introduction to Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To start working with Numpy, We first need to import it.

In [1]:
import numpy as np

Numpy is now imported and we can use it by simply writing "np". Here is how to create an array and print it and its shape:-

In [2]:
a = np.array([1,2,3,4,5])
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


We can also create some special arrays by Numpy functions. For example:- 

In [4]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)   
print("\n")

b = np.ones((3,3))    # Create an array of all ones
print(b)             
print("\n")

c = np.full((1,2), 7)  # Create an array of all elements as one number
print(c) 
print("\n")

d = np.eye(3)         # Create a 3x3 identity matrix
print(d)    
print("\n")

[[0. 0.]
 [0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[7 7]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




Slicing is the way to access sub-parts of our data structures. Here is how to slice an array:-

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = a[:1, 1:3]                           #Here we create an array b with 1st row and all columns between 1st and 4th columns of a
print(b)

[[2 3]]


We can also perform various mathematical operations,which are quite handy, using Numpy. Here is how to do it:-

In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
          
print(np.add(x, y))          # Elementwise sum;
print("\n")

print(np.subtract(x, y))     # Elementwise difference
print("\n")

print(np.multiply(x, y))     # Elementwise product
print("\n")

print(np.divide(x, y))       # Elementwise division
print("\n")

print(np.sqrt(x))            # Elementwise square root
print("\n")

[[ 6  8]
 [10 12]]


[[-4 -4]
 [-4 -4]]


[[ 5 12]
 [21 32]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[1.         1.41421356]
 [1.73205081 2.        ]]




Various Matrix operations can also be performed through Numpy in the following way:-

In [17]:
x = np.array([1,2])
y = np.array([3,4])

print(np.dot(x, y))          #Prints dot product of x and y
print("\n")
              
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
              
print(np.matmul(a, b))       #Prints the matrix product of a and b
print("\n")

print(np.transpose(a))               #Prints transpose of a
print("\n")

print(np.sum(a))  #Prints sum of all elements; prints "10"
print("\n")

print(np.sum(a, axis=0))  #Prints sum of each column; prints "[4 6]"
print("\n")

print(np.sum(a, axis=1))  #Prints sum of each row
print("\n")


11


[[19 22]
 [43 50]]


[[1 3]
 [2 4]]


10


[4 6]


[3 7]




As we have seen Numpy is quite useful as it provides easier wways to do computations. Thus, it is quite popularly used in data science, machine learning, scientific computing, etc.To learn more about Numpy, feel free to go through its documentation at https://numpy.org/doc/.