In [46]:
import numpy as np

# BASICS

1-D array

In [2]:
a = np.array([1,2,3],dtype = "int16")
print(a)

[1 2 3]


2-D array

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b.shape

(2, 3)

In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get type
a.dtype

dtype('int16')

In [7]:
# Get size
a.itemsize

2

In [8]:
# Get total size
a.nbytes

6

In [9]:
b.nbytes

24

In [48]:
#to make an array of equal intervals from a to b
a = np.arange(0,4,0.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

# Modifying matrix

In [11]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
# To get the (i,j) element
a[1,2]

7

In [13]:
# To get a specific row
a[2,:]

array([ 9, 10, 11, 12])

In [14]:
# To get a specific column
a[:,2]

array([ 3,  7, 11])

In [15]:
# To get a subarray
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [16]:
#zeroes and ones matrices
np.ones((2,2),dtype = "int64")

array([[1, 1],
       [1, 1]], dtype=int64)

In [17]:
np.zeros((4,4),dtype = "int32")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
#any other number
np.full((2,2),66,dtype = "float32")
#or
np.full(a.shape,88)

array([[88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88]])

In [19]:
#for random decimal numbers
np.random.rand(4,2)

array([[0.40143331, 0.74908563],
       [0.33366207, 0.01885462],
       [0.91397085, 0.26105394],
       [0.9750579 , 0.8475468 ]])

In [20]:
#integer rand
np.random.randint(-4,10,size = (3,3))

array([[ 3,  3,  6],
       [-4, -1,  5],
       [ 8,  4,  0]])

In [21]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
arr = np.ones((5,5))
arr[1:4,1:4] = 0
arr[2,2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# to copy
a = np.array([1,2])
b = np.copy(a)
b

array([1, 2])

# Mathematics

In [25]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

Elemental operations

In [26]:
a+2

array([3, 4, 5, 6])

In [27]:
a-2

array([-1,  0,  1,  2])

In [28]:
a*2

array([2, 4, 6, 8])

In [29]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [30]:
b = np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [31]:
a**2 #a to the second power

array([ 1,  4,  9, 16], dtype=int32)

In [32]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [33]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# matrix multiplication
np.matmul(b,a)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [34]:
#Det of a matrix
c = np.identity(2)
np.linalg.det(c)

1.0

# Statistics

In [35]:
stats=  np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.min(stats,axis = 1)

array([1, 4])

In [37]:
np.max(stats)

6

In [38]:
np.sum(stats,axis = 0)

array([5, 7, 9])

# Reorganizing arrays

In [39]:
# Reshaping arrays
before = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(before)

after = before.reshape(10,1)
print(after)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [40]:
# Vertically staacking vectors

vec1 = np.array([1,2,3,4])
vec2 = np.array([5,6,7,8])

np.vstack([vec1,vec2,vec2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [41]:
# Horizontally staacking vectors

vec1 = np.array([1,2,3,4])
vec2 = np.array([5,6,7,8])

np.hstack([vec1,vec2,vec2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

# Boolean and other stuff on matrix

In [42]:
a =np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(a)
#for noting which values follow a particular bool
a > 3

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [43]:
#to get elements following the bool
a[a>3]

array([4, 5, 4, 5, 4, 5])

In [44]:
((a > 1) & (a < 3))

array([[False,  True, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

In [45]:
#to open certain indices
a[[1,2],[0,1]]

array([1, 2])